### ISSUE TITLE
Publish v0.0.1

### ISSUE THREAD

**Issue by penandlim** [cowprotocol/ts-dune-client#20]
I dont think 0.0.1 is published on npm yet
https://www.npmjs.com/package/@cowprotocol/ts-dune-client?activeTab=versions

Would be great to see the too many requests fix added in the new release!

**Comment by bh2smith** [comment]
Should be fixed very soon:

https://github.com/cowprotocol/ts-dune-client/releases/tag/v0.0.1

which includes https://github.com/cowprotocol/ts-dune-client/pull/21
